spring:
  application:
    name: muzik
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: "${SPRING_JPA_HIBERNATE_DDL_AUTO}"
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "${JWT_SECRET}"
  expiration: 86400000
